# Generated by Django 5.0.7 on 2024-07-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_alter_spotifytoken_expires_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifytoken',
            name='expires_in',
        ),
    ]
